# https://coryrylan.com/blog/building-angular-cli-projects-with-github-actions

name: Build
on:
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm ci and npm run build
        run: |
          npm ci
          npm run build:ci

      - name: move to dir
        run: |
          mkdir -p output
          yes| cp -rf dist/ ./output/

      - name: Add CNAME
        run: echo "vivekbhat.me" > dist/CNAME

      - name: Running command
        run: ls

      - name: Dist folder
        run: ls dist

      - name: Key
        run: echo ${{ secrets.GITHUB_TOKEN }}

      - name: check git config
        run: |
          git config --global user.email "vivekbhat@live.com"
          git config --global user.name "vivekbhat"
          git config --local user.email "vivekbhat@live.com"
          git config --local user.name "vivekbhat"
          git config --global commit.gpgsign true
          git config -l

      - name: Commit files
        shell: bash
        run: |
          git add dist/
          git commit -S -m "dist added"
        env:
          GIT_TRACE: 1

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: B77
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true

      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"

  #      - name: upload artifacts
  #        uses: actions/upload-artifact@master
  #        with:
  #          name: webpack artifacts
  #          path: dist
