# https://coryrylan.com/blog/building-angular-cli-projects-with-github-actions

name: Build
on:
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm ci and npm run build
        run: |
          npm ci
          npm run build:ci

      - name: Running command
        run: ls

      - name: Add CNAME
        run: echo "vivekbhat.me" > dist/CNAME

      - name: upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: webpack artifacts
          path: dist

  Download-Artifacts:
    runs-on: ubuntu-latest
    needs: Build
    strategy:
      matrix:
        node-version: [12.x]
    name: Docker Build, Tag, Push
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Download built artifact
        uses: actions/download-artifact@master
        with:
          name: webpack artifacts
          path: public

      - name: Running command
        run: ls public/
